feat happy-arch-chroot
Growthers/blog-data pull request #39
Opened 2022-05-22 14:46 UTC by YukiYuigishi

記事名「wpa_supplicantを入れ忘れたのでAlterでarch-chrootした話」

2022-05-22 14:49 UTC, Sigumaa submitted a review, later dismissed

2022-05-22 14:50 UTC, laminne requested changes
Alt属性がないので書いてください

2022-05-22 14:50 UTC, laminne commented on articles/yuki/happy-arch-chroot/index.md
> +[](https://imgur.com/BXEu8KQ.jpg)
Alt書いてください

2022-05-22 14:50 UTC, laminne commented on articles/yuki/happy-arch-chroot/index.md
> +[](https://images-ext-2.discordapp.net/external/JanmE90PISF8maPrUOTYYNpfsf6BW5IagmyJJATdr1E/https/i.imgur.com/YVUVUt3.png)
ここも

2022-05-22 14:54 UTC, laminne approved these changes

2022-05-23 02:38 UTC, Yusuke4869 approved these changes

2022-05-23 02:39 UTC, merged